dist: trusty
sudo: required
language: cpp

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test 
  - sudo apt-get update  
  - sudo apt-get install -qq g++-6 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60  
  - cd lesson4_print_ip
script:
  - cmake .
  - cmake --build .
  - ls /home/travis/build/avovana/tasks/lesson4_print_ip
#  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uavovana:$BINTRAY_API_KEY "https://api.bintray.com/content/avovana/tasks/4lesson_print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
